apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: nk70mab02-java-springboot-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/nk70mab02-java-springboot-gitops